package org.collegemanagement.services;

import org.collegemanagement.entity.finance.Payment;
import org.collegemanagement.enums.PaymentGateway;

import java.math.BigDecimal;

/**
 * Service interface for payment gateway integration.
 * Follows Strategy pattern to support multiple payment gateways.
 * <p>
 * TODO: Integrate payment gateway
 * - Implement actual gateway API calls
 * - Handle gateway-specific request/response formats
 * - Implement webhook handling for payment status updates
 * - Add retry logic for failed requests
 * - Implement idempotency checks
 */

public interface PaymentGatewayService {

    /**
     * Create a payment order with the gateway.
     *
     * @return gatewayOrderId generated by the gateway
     */
    String createOrder(Payment payment, BigDecimal amount);

    /**
     * Verify webhook signature (gateway-specific)
     */
    boolean verifyWebhookSignature(
            PaymentGateway gateway,
            String payload,
            String signature
    );
}


